networks:
  minio:
    driver: bridge

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    networks:
      - minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/minio/health/ready || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5

  create-buckets:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - minio
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      mc alias set s3 http://minio:9000 user password;
      mc mb --ignore-existing s3/nvdb-tnits-local-data-01;
      exit 0;
      '

  local-oauth:
    image: ghcr.io/navikt/mock-oauth2-server:3.0.1
    container_name: nvdb-local-oauth
    ports:
      - "8099:8080"
    volumes:
      - ./docker-compose/local-oauth:/config
    environment:
      JSON_CONFIG_PATH: /config/config.json
